# Generated by Django 2.2 on 2019-04-13 14:41
from django.core.management import call_command
from django.db import migrations


def forward(_, __):
    call_command("createcachetable")


def backward(_, __):
    pass


class Migration(migrations.Migration):

    dependencies = [("pipeline", "0015_auto_20190412_1304")]

    operations = [migrations.RunPython(forward, backward)]
