# Generated by Django 2.2 on 2019-04-14 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pipeline", "0016_create_cache_table")]

    operations = [
        migrations.AddField(
            model_name="videoformat",
            name="height",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="videoformat",
            name="width",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
